// Racing Atelier design tokens for the rig screen UI.
//
// Source of truth:
// - docs/10_Development/design/racing-atelier/project/tokens/*.css
// - docs/10_Development/design/racing-atelier-renders/esp32_rig.png
//
// Keep the legacy token names where screen code already uses them, but map
// their values to the Racing Atelier carbon/brass/signal palette.

#pragma once

#include <lvgl.h>

/* Racing Atelier LVGL font bundle (generated by lv_font_conv). */
LV_FONT_DECLARE(font_saira_sc_black_54);
LV_FONT_DECLARE(font_saira_sc_bold_34);
LV_FONT_DECLARE(font_saira_sc_bold_28);
LV_FONT_DECLARE(font_saira_sc_semibold_12);
LV_FONT_DECLARE(font_saira_sc_semibold_11);
LV_FONT_DECLARE(font_saira_sc_semibold_9);
LV_FONT_DECLARE(font_saira_bold_46);
LV_FONT_DECLARE(font_saira_bold_34);
LV_FONT_DECLARE(font_saira_bold_26);
LV_FONT_DECLARE(font_spline_mono_12);
LV_FONT_DECLARE(font_spline_mono_11);
LV_FONT_DECLARE(font_spline_mono_10);

#define UI_FONT_COMMAND_HERO  (&font_saira_sc_black_54)
#define UI_FONT_COMMAND_MD    (&font_saira_sc_bold_34)
#define UI_FONT_COMMAND_SM    (&font_saira_sc_bold_28)
#define UI_FONT_LABEL_MD      (&font_saira_sc_semibold_12)
#define UI_FONT_LABEL_SM      (&font_saira_sc_semibold_11)
#define UI_FONT_LABEL_XS      (&font_saira_sc_semibold_9)
#define UI_FONT_READ_XL       (&font_saira_bold_46)
#define UI_FONT_READ_LG       (&font_saira_bold_34)
#define UI_FONT_READ_MD       (&font_saira_bold_26)
#define UI_FONT_MONO_MD       (&font_spline_mono_12)
#define UI_FONT_MONO_SM       (&font_spline_mono_11)
#define UI_FONT_MONO_XS       (&font_spline_mono_10)

/* Backgrounds */
#define UI_BG_BASE          lv_color_hex(0x0B0C0D)   /* carbon */
#define UI_BG_PANEL         lv_color_hex(0x141618)   /* graphite */
#define UI_BG_PANEL_OPA     LV_OPA_COVER
#define UI_BG_HEADER        lv_color_hex(0x191C1F)   /* slab */
#define UI_BG_HEADER_OPA    LV_OPA_COVER
#define UI_BG_RAISE         lv_color_hex(0x20242A)

/* Text */
#define UI_TX_PRIMARY       lv_color_hex(0xEEF1F3)   /* chalk */
#define UI_TX_MUTED         lv_color_hex(0x9BA1A8)
#define UI_TX_QUIET         lv_color_hex(0x79808A)
#define UI_TX_FAINT         lv_color_hex(0x4A4E55)

/* Accents and state fields */
#define UI_BRASS            lv_color_hex(0xC8983E)
#define UI_BRASS_INK        lv_color_hex(0x0B0C0D)
#define UI_ACCENT_GOLD      UI_BRASS      /* legacy name */
#define UI_ALERT_RED        lv_color_hex(0xF23B2C)
#define UI_OK_GREEN         lv_color_hex(0x2FBE6E)
#define UI_LINE_AMBER       lv_color_hex(0xF4A52C)
#define UI_DATA_CYAN        lv_color_hex(0x49B6C9)

/* Borders */
#define UI_BORDER_SOFT      lv_color_hex(0x2A2F35)
#define UI_BORDER_SOFT_OPA  LV_OPA_COVER
#define UI_BORDER_ALERT     UI_ALERT_RED
#define UI_BORDER_ALERT_OPA LV_OPA_COVER

/* Layout */
#define UI_TAP_MIN_PX       60
#define UI_RADIUS_TILE      0
#define UI_GAP_TILES        12

/* Animation */
#define UI_ANIM_PRESS_MS    120
#define UI_ANIM_PRESS_SCALE 251
