"""Bootstrap knowledge script (SQLite seeding from markdown)."""

from __future__ import annotations

import importlib.util
import sqlite3
import sys
from pathlib import Path
from types import ModuleType

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]


def _load_bootstrap() -> ModuleType:
    path = REPO_ROOT / "scripts" / "bootstrap_knowledge.py"
    spec = importlib.util.spec_from_file_location("_bootstrap_knowledge_test", path)
    assert spec is not None, f"failed to create spec for {path}"
    assert spec.loader is not None, f"spec has no loader for {path}"
    mod = importlib.util.module_from_spec(spec)
    sys.modules["_bootstrap_knowledge_test"] = mod
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture
def bootstrap_mod():
    return _load_bootstrap()


def test_bootstrap_seeds_patterns_and_is_idempotent(tmp_path: Path, bootstrap_mod) -> None:
    (tmp_path / "AGENTS.md").write_text(
        "## Learned User Preferences\n\n"
        "- **Pref** — one preference line.\n\n"
        "## Learned Workspace Facts\n\n"
        "- One workspace fact.\n\n"
        "## Changelog\n\nx\n",
        encoding="utf-8",
    )
    (tmp_path / "AGENT_CORE_PRINCIPLES.md").write_text(
        "# Principles\n\n1. Numbered principle alpha.\n",
        encoding="utf-8",
    )
    inv = tmp_path / "docs/01_Vault/AcCopilotTrainer/00_System/invariants"
    inv.mkdir(parents=True)
    (inv / "sample.md").write_text(
        "---\ntype: invariant\n---\n\n# Invariant: sample\n\n## Rule\n\nAlways sample.\n",
        encoding="utf-8",
    )

    assert bootstrap_mod.bootstrap(root=tmp_path) == 0
    assert bootstrap_mod.bootstrap(root=tmp_path) == 0

    db_path = tmp_path / ".cache/repo_knowledge/knowledge.db"
    assert db_path.is_file()
    conn = sqlite3.connect(db_path)
    try:
        n_patterns = conn.execute("SELECT COUNT(*) FROM patterns").fetchone()[0]
        pattern_texts = {row[0] for row in conn.execute("SELECT pattern_text FROM patterns")}
        n_evidence = conn.execute(
            "SELECT COUNT(*) FROM pattern_evidence WHERE comment_author = ?",
            ("bootstrap_knowledge",),
        ).fetchone()[0]
        n_decisions = conn.execute(
            "SELECT COUNT(*) FROM decisions WHERE rationale = ?",
            ("bootstrap_knowledge",),
        ).fetchone()[0]
        dup = conn.execute(
            "SELECT 1 FROM patterns WHERE pattern_text LIKE 'Invariant: Invariant:%' LIMIT 1"
        ).fetchone()
        assert dup is None
        assert "Invariant: sample" in pattern_texts
    finally:
        conn.close()

    assert n_patterns == 4
    assert n_evidence == 4
    assert n_decisions == 1


def test_strip_frontmatter_does_not_split_inline_triple_dash(bootstrap_mod) -> None:
    """Values may contain ``---``; only a newline-delimited close must end frontmatter."""
    text = (
        "---\n"
        "type: invariant\n"
        "description: use --- separator\n"
        "---\n"
        "\n"
        "# Invariant: dashy\n\n## Rule\n\nok.\n"
    )
    body = bootstrap_mod._strip_frontmatter(text)
    assert body.startswith("# Invariant: dashy")
    assert "## Rule" in body
    assert "description:" not in body


def test_bootstrap_ignores_process_miner_autogen_block(tmp_path: Path, bootstrap_mod) -> None:
    """Autogenerated process-miner markers must not become SQLite patterns."""
    (tmp_path / "AGENTS.md").write_text(
        "## Learned User Preferences\n\n"
        "- Human preference.\n\n"
        "## Learned Workspace Facts\n\n"
        "- Human fact.\n"
        "<!-- process-miner:learned:start -->\n"
        "- (process-miner) New learned rule file(s): x.md\n"
        "<!-- process-miner:learned:end -->\n\n"
        "## Changelog\n\nx\n",
        encoding="utf-8",
    )
    (tmp_path / "AGENT_CORE_PRINCIPLES.md").write_text(
        "# Principles\n\n1. One principle.\n",
        encoding="utf-8",
    )

    assert bootstrap_mod.bootstrap(root=tmp_path) == 0

    db_path = tmp_path / ".cache/repo_knowledge/knowledge.db"
    conn = sqlite3.connect(db_path)
    try:
        texts = {row[0] for row in conn.execute("SELECT pattern_text FROM patterns")}
    finally:
        conn.close()

    assert "Human preference." in texts
    assert "Human fact." in texts
    assert not any("process-miner" in t for t in texts)
