#!/usr/bin/env python3
"""Classify changed paths from a merged PR for post-merge follow-ups.

Reads paths from ``gh pr diff <N> --name-only``, stdin (one path per line), or ``--file``.
Prints a short actionable summary to stdout. Optionally posts a Markdown comment via ``gh``.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


def normalize_paths(paths: list[str]) -> list[str]:
    out: list[str] = []
    for raw in paths:
        p = raw.strip().replace("\\", "/")
        if p:
            out.append(p)
    return out


def classify_changed_paths(paths: list[str]) -> list[str]:
    """Return ordered human-readable follow-up lines (no duplicates)."""
    norm = normalize_paths(paths)
    if not norm:
        return []

    messages: list[str] = []
    seen: set[str] = set()

    def add(key: str, text: str) -> None:
        if key not in seen:
            seen.add(key)
            messages.append(text)

    if any(
        "alembic/versions/" in p
        or "/migrations/" in p
        or p.startswith(("migrations/", "db/migrations/"))
        for p in norm
    ):
        add(
            "migration",
            "Migration paths touched: run your project's migrate command "
            "(e.g. `alembic upgrade head`).",
        )

    if any(p == ".env.example" or p.endswith("/.env.example") for p in norm):
        add(
            "env_example",
            "`.env.example` changed: review for new required environment variables.",
        )

    if any(p == "pyproject.toml" or p.endswith("/pyproject.toml") for p in norm):
        add(
            "deps",
            "`pyproject.toml` changed: run `pip install -e '.[dev]'` (or your lockfile workflow).",
        )

    if any(p.startswith("scripts/") for p in norm):
        add(
            "scripts",
            "`scripts/` changed: review new or updated setup/utility scripts.",
        )

    if any(p.startswith(".github/workflows/") for p in norm):
        add(
            "workflows",
            "`.github/workflows/` changed: review triggers, permissions, and secrets usage.",
        )

    if any(Path(p).name == "Makefile" for p in norm):
        add(
            "makefile",
            "`Makefile` changed: check for new targets and document if needed.",
        )

    return messages


def _format_comment(lines: list[str]) -> str:
    body = "## Post-merge follow-ups\n\n"
    body += "\n".join(f"- {line}" for line in lines)
    body += "\n\n_Auto-generated by post-merge classification._"
    return body


def _paths_from_gh_pr(pr: int) -> list[str]:
    if shutil.which("gh") is None:
        print("error: gh CLI not found", file=sys.stderr)
        sys.exit(1)
    r = subprocess.run(
        ["gh", "pr", "diff", str(pr), "--name-only"],
        check=False,
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        print(r.stderr.strip() or "gh pr diff failed", file=sys.stderr)
        sys.exit(r.returncode or 1)
    return [ln for ln in r.stdout.splitlines() if ln.strip()]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    src = parser.add_mutually_exclusive_group(required=False)
    src.add_argument("--pr", type=int, metavar="N", help="GitHub PR number (uses gh pr diff)")
    src.add_argument(
        "--file",
        type=Path,
        help="Read paths from file (one per line)",
    )
    parser.add_argument(
        "--github-comment",
        action="store_true",
        help="Post results as a PR comment (requires --pr and gh auth)",
    )
    args = parser.parse_args()

    if args.github_comment and args.pr is None:
        parser.error("--github-comment requires --pr")

    if (args.github_comment or args.pr is not None) and not shutil.which("gh"):
        print("error: gh CLI not found", file=sys.stderr)
        sys.exit(1)

    paths: list[str]
    if args.file is not None:
        if not args.file.is_file():
            parser.error(f"file not found: {args.file}")
        paths = args.file.read_text(encoding="utf-8").splitlines()
    elif args.pr is not None:
        paths = _paths_from_gh_pr(args.pr)
    else:
        if sys.stdin.isatty():
            parser.error("provide --pr, --file, or pipe path list on stdin")
        paths = sys.stdin.read().splitlines()

    lines = classify_changed_paths(paths)
    if not lines:
        print("No post-merge classification flags for these paths.")
        return

    text = "\n".join(lines)
    print(text)

    if args.github_comment:
        body = _format_comment(lines)
        if shutil.which("gh") is None:
            sys.exit(1)
        pr_num = str(args.pr)
        subprocess.run(
            ["gh", "pr", "comment", pr_num, "--body-file", "-"],
            input=body,
            text=True,
            check=True,
        )


if __name__ == "__main__":
    main()
